// Auto-generated by LibreLane
module croctop(
`ifdef USE_POWER_PINS
  inout VDD,
  inout VSS,
  inout IOVDD,
  inout IOVSS,
`endif
  inout clk_i,
  inout rst_ni,
  inout ref_clk_i,
  inout[3:0] jtag_inputs_PAD,
  output jtag_tdo_o,
  inout uart_rx_i,
  output uart_tx_o,
  inout fetch_en_i,
  output status_o,
  inout[31:0] gpio_io,
  output[3:0] unused_o
);
endmodule
