// Auto-generated by LibreLane
module top(
`ifdef USE_POWER_PINS
  inout VDD,
  inout VSS,
  inout IOVDD,
  inout IOVSS,
`endif
  inout clk_PAD,
  inout rst_n_PAD,
  inout in_valid_PAD,
  inout[7:0] in_data_PADs,
  output in_ready_PAD,
  output out_valid_PAD,
  inout out_ready_PAD,
  output[7:0] out_data_PADs
);
endmodule
